# Use official PHP image with FPM
FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    nginx \
    && docker-php-ext-install pdo pdo_pgsql

# Set working directory
WORKDIR /var/www

# Copy Laravel app
COPY . .

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install dependencies
RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress

# Permissions for Laravel storage & cache
RUN chmod -R 777 storage bootstrap/cache

# Copy default Nginx config
COPY .docker/nginx/default.conf /etc/nginx/sites-available/default

# Expose port 8000 for Laravel
EXPOSE 8000

# Start PHP-FPM & Nginx
CMD ["php-fpm", "-D", "&&", "nginx", "-g", "daemon off;"]
